language: node_js
dist: trusty
node_js:
  - "8"

addons:
  chrome: stable

sudo: required

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run test:ci
  - npm run lint
  - npm run build:prod -- --base-href "https://tariknz.github.io/reddit-pwa/"
  - npm run ngsw-config -- "https://tariknz.github.io/reddit-pwa/"

after_success:
  - npm run publish:ci

notifications:
  email:
    on_failure: change
    on_success: change
