language: node_js
node_js:
  - "8"

addons:
  chrome: stable

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

install:
  - npm install

script:
  - npm run test -- --single-run

after_success:
  - npm run publish

notifications:
  email:
    on_failure: change
    on_success: change