language: node_js
dist: trusty
node_js:
  - "8"

addons:
  chrome: stable

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run test:ci

after_success:
  - npm run publish:ci

notifications:
  email:
    on_failure: change
    on_success: change